linters:
  enable-all: true
  disable:
    - typecheck
    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - paralleltest
    - cyclop # todo
    - errorlint # todo
    - funlen # todo
    - gci # todo
    - gocognit # todo
    - godox # todo
    - goerr113 # todo
    - lll # todo
    - prealloc # todo
    - revive # todo
    - varnamelen # todo
    - wrapcheck # todo
