linters:
  enable-all: true
  disable:
    - tenv # deprecated
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - paralleltest
    - typecheck
    - cyclop # todo
    - err113 # todo
    - errorlint # todo
    - funlen # todo
    - gci # todo
    - gocognit # todo
    - godox # todo
    - lll # todo
    - prealloc # todo
    - revive # todo
    - varnamelen # todo
    - wrapcheck # todo
